/**
 * ConversationMessageType Enum
 *
 * Defines the type of message in a conversation thread.
 * Used to distinguish between user input, AI responses, and system messages.
 */
export enum ConversationMessageType {
  /** Message sent by the user */
  USER = 'user',

  /** Response generated by the AI assistant */
  ASSISTANT = 'assistant',

  /** System-generated message (e.g., errors, notifications) */
  SYSTEM = 'system',
}
